### ISSUE TITLE
qq音乐cookie无法覆盖

### ISSUE THREAD

**Issue by YangZhaocool** [WowYiJiu/Personal#2]
当签到脚本提示cookie失效后
重新获取cookie时提示xxxx已存在 本次不再重新获取 此时如果再次运行qq音乐的签到脚本的话 依旧提示cookie失效

**Comment by WowYiJiu** [comment]
我没写失效时删除cookie，暂时得手动到boxjs删除，现在QQ音乐页面任务都没了，也不想改了
