### ISSUE TITLE
txSports 获取cookie运行后报错自动删除cookies

### ISSUE THREAD

**Issue by bserho** [WowYiJiu/Personal#3]
Logs:

🔔腾讯体育, 开始!

❗️腾讯体育, 错误!
SyntaxError: JSON Parse error: Unable to parse JSON string
👾 获取免责声明失败

🍒 当前版本：v1.0.1  最新版本：v1.0.1

===============  🤪 任务 🤪  ===============
❗️签到失败：Cookie失效, 已清除
请重新获取Cookie
💎 随机延迟2198ms后继续执行

===============  📣 通知 📣  ===============
腾讯体育
🍒 当前版本：v1.0.1  最新版本：v1.0.1
❗️签到失败：Cookie失效，已清除
请重新获取Cookie

🔔腾讯体育, 结束! 🕛 13.329 秒

**Comment by WowYiJiu** [comment]
Cookie需要的字段变了，vqq_vusession值有效期也变短了，暂时还没解决

**Comment by WowYiJiu** [comment]
> Logs:
> 
> 🔔腾讯体育, 开始!
> 
> ❗️腾讯体育, 错误! SyntaxError: JSON Parse error: Unable to parse JSON string 👾 获取免责声明失败
> 
> 🍒 当前版本：v1.0.1 最新版本：v1.0.1
> 
> =============== 🤪 任务 🤪 =============== ❗️签到失败：Cookie失效, 已清除 请重新获取Cookie 💎 随机延迟2198ms后继续执行
> 
> =============== 📣 通知 📣 =============== 腾讯体育 🍒 当前版本：v1.0.1 最新版本：v1.0.1 ❗️签到失败：Cookie失效，已清除 请重新获取Cookie
> 
> 🔔腾讯体育, 结束! 🕛 13.329 秒

Cookie需要的字段变了，vqq_vusession值有效期也变短了，暂时还没解决

**Comment by WowYiJiu** [comment]
> Logs:
> 
> 🔔腾讯体育, 开始!
> 
> ❗️腾讯体育, 错误! SyntaxError: JSON Parse error: Unable to parse JSON string 👾 获取免责声明失败
> 
> 🍒 当前版本：v1.0.1 最新版本：v1.0.1
> 
> =============== 🤪 任务 🤪 =============== ❗️签到失败：Cookie失效, 已清除 请重新获取Cookie 💎 随机延迟2198ms后继续执行
> 
> =============== 📣 通知 📣 =============== 腾讯体育 🍒 当前版本：v1.0.1 最新版本：v1.0.1 ❗️签到失败：Cookie失效，已清除 请重新获取Cookie
> 
> 🔔腾讯体育, 结束! 🕛 13.329 秒

已更新，最新的看tenvideo.js
